services:
  - type: web
    name: whatcha-lookin-for-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python backend/start.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0 